apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: image-repo-credentials
  namespace: 
spec:
  encryptedData:
    config: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq
    known_hosts: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq
  template:
    metadata:
      name: image-repo-credentials
      namespace:
    type: Opaque